### PR TITLE
docs: migration guide and other documentation improvements

### LINKED ISSUE #1326: The "from" argument must be of type string. Received type undefined
I am trying to use steps I wrote and publish on npm
Here is the error I have:
```
> cucumber-js e2e/src/**/*.feature --require ./node_modules/@myProject/uat/dist/*.step.js

TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received type undefined
at validateString (internal/validators.js:125:11)
at Object.relative (path.js:1162:5)
at getDefinitionLineAndUri (/home/myname/Documents/myProject/mysubProjectV2/node_modules/@myProject/uat/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:184:27)
at buildStepDefinitionConfig (/home/myname/Documents/myProject/mysubProjectV2/node_modules/@myProject/uat/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:124:7)
at SupportCodeLibraryBuilder.defineStep (/home/myname/Documents/myProject/mysubProjectV2/node_modules/@myProject/uat/node_modules/cucumber/lib/support_code_library_builder/index.js:51:79)
at Object.<anonymous> (/home/myname/Documents/myProject/mysubProjectV2/node_modules/@myProject/uat/dist/click.step.js:40:12)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at supportCodePaths.forEach.codePath (/home/myname/Documents/myProject/mysubProjectV2/node_modules/cucumber/lib/cli/index.js:142:42)
at Array.forEach (<anonymous>)
at Cli.getSupportCodeLibrary (/home/myname/Documents/myProject/mysubProjectV2/node_modules/cucumber/lib/cli/index.js:142:22)
```

I have found that this is ```this.cwd``` which is undefined. What can i do?
image

If I copy paste my steps in the root directory (where the package.json is), I don't have any error. So the problem is: I cannot not --require from node_modules.

### LINKED ISSUE #1517: Custom TeamCity formatter is no longer working with version 7.0.0
We are using a custom TeamCity formatter for our BDD tests which is defined in the `bdd/formatters/cucumber-teamcity-formatter.js` file in the repository.

Since the upgrade of the Cucumber version from `7.0.0-rc.0` to `7.0.0` we started getting an error when running it:

```
Error: Cannot find module 'bdd/formatters/cucumber-teamcity-formatter'
Require stack:
- C:\GitHub\ecomm-gate\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

The command used is `cucumber-js --format bdd/formatters/cucumber-teamcity-formatter --require 'bdd/**/*.js' bdd/features/**/*.feature`

### LINKED ISSUE #1520: Guidelines for upgrade to cucumber 7?
Hello,

any guidelines how to upgrade from cucumber 5.1.0 to @cucumber/cucumber 7.0.0?

### LINKED ISSUE #1546: [docs] Custom Formatters doc mentions a deprecated formatter
Hello Cucumber team,

Unless I am wrong, it seems to me that the [Extending Built-Ins section](https://github.com/cucumber/cucumber-js/blob/master/docs/custom_formatters.md#extending-built-ins) in `custom_formatters.md` mentions that `PrettyFormatter` inherits from `SummaryFormatter` , but I do not see any builtin `Pretty` formatter in the v7 code base.

### PR DESCRIPTION
**Pull request by davidjgoss**
- Add a dedicated migration guide, link to it from main readme and changelog
- Update formatter docs to be more readable and specify different flavours of formatter descriptor (fixes #1517)
- Update docs on parallel now that we fixed the timing in the summary formatter
- Add advice for distribution of custom formatters
- Modernise the documentation around `World` (fixes #1520)
- Fix the package name in documentation examples
- Remove reference to built-in pretty formatter (fixes #1546)
- Document a common issue (and workaround) from npm linking step libraries (fixes #1326)

### CODE REVIEW

**Review by charlierudolph — APPROVED** [review]

**Comment by charlierudolph** [comment]
Looks great! Thanks for updating it

**Comment by dmitriyKowWib** [comment]
Trying to migrate from cucumber js 6 to 7. Have may issues:
1) Typescript compilatiin error in your code:
`node_modules/@cucumber/messages/dist/src/index.d.ts:9:25 - error TS2732: Cannot find module '../package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

9 import { version } from '../package.json';
                          ~~~~~~~~~~~~~~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:642:35 - error TS2304: Cannot find name 'Long'.

642                 seconds?: (number|Long|null);
                                      ~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:658:41 - error TS2304: Cannot find name 'Long'.

658                 public seconds: (number|Long);
                                            ~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:738:35 - error TS2304: Cannot find name 'Long'.

738                 seconds?: (number|Long|null);
                                      ~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:754:41 - error TS2304: Cannot find name 'Long'.

754                 public seconds: (number|Long);
`
There are no clear documentation how to rewrite webhooks.
`steps/globalHooks.ts:150:1 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(tags: string, code: TestCaseHookFunction): void', gave the following error.
    Argument of type '{ tags: string; }' is not assignable to parameter of type 'string'.
  Overload 2 of 3, '(options: IDefineTestCaseHookOptions, code: TestCaseHookFunction): void', gave the following error.
    Argument of type '() => string' is not assignable to parameter of type 'TestCaseHookFunction'.
      Type '() => string' is not assignable to type 'TestCaseHookFunctionWithoutParameter'.
        Type 'string' is not assignable to type 'void | Promise<void>'.

150 Before({tags: "@only_morning_run"}, function () {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
151     const now = new Date();
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
155     }
    ~~~~~
156 });
    ~~
`

**Comment by aslakhellesoy** [comment]
@dmitriyKowWib please open a new issue. We don't keep an eye on closed issues and merged PRs.
