### ISSUE TITLE
Custom TeamCity formatter is no longer working with version 7.0.0

### ISSUE THREAD

**Issue by mmajkafmp** [cucumber/cucumber-js#1517]
We are using a custom TeamCity formatter for our BDD tests which is defined in the `bdd/formatters/cucumber-teamcity-formatter.js` file in the repository.

Since the upgrade of the Cucumber version from `7.0.0-rc.0` to `7.0.0` we started getting an error when running it:

```
Error: Cannot find module 'bdd/formatters/cucumber-teamcity-formatter'
Require stack:
- C:\GitHub\ecomm-gate\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

The command used is `cucumber-js --format bdd/formatters/cucumber-teamcity-formatter --require 'bdd/**/*.js' bdd/features/**/*.feature`

**Comment by davidjgoss** [comment]
Thanks for raising @mmajkafmp 

One of the changes in 7.0.0 is to how you express paths to formatters. Now, any string that doesn't start with "./" will be treated like a module descriptor and `require`'d - I think in your case you just need to change to

```shell
cucumber-js --format ./bdd/formatters/cucumber-teamcity-formatter --require 'bdd/**/*.js' bdd/features/**/*.feature
```

Let me know how that goes.

**Comment by mmajkafmp** [comment]
> Thanks for raising @mmajkafmp
> 
> One of the changes in 7.0.0 is to how you express paths to formatters. Now, any string that doesn't start with "./" will be treated like a module descriptor and `require`'d - I think in your case you just need to change to
> 
> ```shell
> cucumber-js --format ./bdd/formatters/cucumber-teamcity-formatter --require 'bdd/**/*.js' bdd/features/**/*.feature
> ```
> 
> Let me know how that goes.

Yes, @davidjgoss. That worked! It might be a good idea to update the documentation on that. Thanks!
